testing:
    hostname: dev1.prestoheads.com
    user: www-data
    port: 22
    forwardAgent: true
    multiplexing: true
    sshOptions:
        UserKnownHostsFile: /dev/null
        StrictHostKeyChecking: no
    stage: staging
    roles:
        - app
        - db
    deploy_path: /var/www/testing-laravelnuxtskeleton.dev1.prestoheads.com
    extra_param: "foo {{hostname}}"
produuction:
    hostname: prod1.prestoheads.com
    user: www-data
    port: 22
    forwardAgent: true
    multiplexing: true
    sshOptions:
        UserKnownHostsFile: /dev/null
        StrictHostKeyChecking: no
    stage: production
    roles:
        - app
        - db
    deploy_path: /var/www/domain.prod1.prestoheads.com
    extra_param: "foo {{hostname}}"
